### ISSUE TITLE
error in landscapeTrashDayResult para

### ISSUE THREAD

**Issue by Doughboy99** [DeanoNoire/MMM-DumpsterDay#1]
if (enableLandscape == true){
	landscapeTrashDayResult = this.isPlasticTrashDay();
	Log.info("landscapeTrashDayResult: "+landscapeTrashDayResult);
	var landscapeDiv = document.createElement("div");
	landscapeDiv.className = "landscapeDiv";
	wrapper.appendChild(landscapeDiv);
		if (landscapeTrashDayResult == 0){
		landscapeDiv.classList.add("non_today")
		}

line 83 should read

landscapeTrashDayResult = this.isLandscapeTrashDay();

**Comment by DeanoNoire** [comment]
Corrected. Thanks!
